apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ufc-events.fullname" . }}-mysql-pv
  labels:
  {{- include "ufc-events.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data