apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ufc-events.fullname" . }}-mysql-pvc
  labels:
  {{- include "ufc-events.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mysqlPvc.storageRequest | quote }}