apiVersion: v1
kind: Service
metadata:
  name: {{ include "ufc-events.fullname" . }}-scrapper-api
  labels:
  {{- include "ufc-events.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scrapperApi.type }}
  selector:
    app: ufc-scrapper-api
  {{- include "ufc-events.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.scrapperApi.ports | toYaml | nindent 2 }}