apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ufc-events.fullname" . }}-python-webscrapper
  labels:
  {{- include "ufc-events.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pythonWebscrapper.replicas }}
  selector:
    matchLabels:
      app: ufc-python-webscrapper
    {{- include "ufc-events.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ufc-python-webscrapper
      {{- include "ufc-events.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: {{ quote .Values.pythonWebscrapper.ufcPythonWebscrapper.env.dbHost }}
        - name: DB_PORT
          value: {{ quote .Values.pythonWebscrapper.ufcPythonWebscrapper.env.dbPort }}
        - name: DB_USER
          value: {{ quote .Values.pythonWebscrapper.ufcPythonWebscrapper.env.dbUser }}
        - name: DB_PASS
          value: {{ quote .Values.pythonWebscrapper.ufcPythonWebscrapper.env.dbPass }}
        - name: DB_NAME
          value: {{ quote .Values.pythonWebscrapper.ufcPythonWebscrapper.env.dbName }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.pythonWebscrapper.ufcPythonWebscrapper.image.repository }}:{{
          .Values.pythonWebscrapper.ufcPythonWebscrapper.image.tag | default .Chart.AppVersion
          }}
        name: ufc-python-webscrapper
        resources: {}