pipeline {
    agent {
        docker {
            image 'edthegreat/jenkins-docker-agent'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials('DOCKERHUB_CREDENTIALS')
    }

    stages {
        stage('SCM Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/eddiegaeta/ufc_webscrapper.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('ufc_mysql_db') {
                    sh 'docker build -t edthegreat/ufc_mysql_db:$BUILD_NUMBER .'
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                dir('ufc_mysql_db') {
                    withCredentials([usernamePassword(credentialsId: 'DOCKERHUB_CREDENTIALS', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                        sh '''
                        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                        '''
                    }
                }
            }
        }

        stage('Push Image') {
            steps {
                dir('ufc_mysql_db') {
                    sh 'docker push edthegreat/ufc_mysql_db:$BUILD_NUMBER'
                }
            }
        }
    }

    post {
        always {
            script {
                docker.image('edthegreat/jenkins-docker-agent').inside('-v /var/run/docker.sock:/var/run/docker.sock') {
                    dir('ufc_mysql_db') {
                        sh 'docker logout'
                    }
                }
            }
        }
    }
}
