pipeline {
    agent any 
    environment {
    DOCKERHUB_CREDENTIALS = credentials('edthegreat-dockerhub')
    }
    stages { 
        stage('SCM Checkout') {
            steps{
            sh 'git fetch --tags --force --progress -- https://github.com/eddiegaeta/ufc_webscrapper.git +refs/heads/*:refs/remotes/origin/* /var/lib/jenkins/workspace/UFC-webscrapper-nodeapi-docker-builder/.git'
            //git 'https://github.com/eddiegaeta/ufc_webscrapper.git'
            }
        }

        stage('Build docker image') {
            steps {  
                sh 'cd /api'
                sh 'docker build -t edthegreat/nodeapi:$BUILD_NUMBER .'
            }
        }
        stage('login to dockerhub') {
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('push image') {
            steps{
                sh 'docker push edthegreat/nodeapi:$BUILD_NUMBER'
            }
        }
}
post {
        always {
            sh 'docker logout'
        }
    }
}
